title: Lucas’ Zion
author: Lucas Evan Li
email: lilujia747@126.com
description: > # this means to ignore newlines until "baseurl:"
  The spiritual asylum of a reclusive soul  
  built of leaves and melodies  
  secluded from the chaotic world.
theme: minima

# social links
instagram_username:  iamlucasli # DO NOT include the @ character, or else the build will fail!
github_username:  Lucas-Evan # DO NOT include the @ character, or else the build will fail!
douban_username:  逸者路加 

show_excerpts: true # set to false to remove excerpts on the homepage
